# fly.toml file generated for pokedex-eacerbi on 2023-03-06T17:29:01-03:00

app = "pokedex-eacerbi"
kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.script_checks]]
    command       = "/app/health_check.sh"
    grace_period  = "2s"
    interval      = "10s"
    restart_limit = 0
    timeout       = "1s"
